### ISSUE TITLE
practica 1

### ISSUE THREAD

**Issue by grupohernandezalba** [LGsusMx/GeoReferenciados-Practica1#1]
Ya casi queda @LGsusMx  , solo me esta mandando un error puede ser la API KEY usa la que subí en el Drive Compatido http://bit.ly/sistemasgeo

**Comment by LGsusMx** [comment]
Profesor, justo cuando cambie a la API que se encuentra en el drive (La que se encuentra en la carpeta practicas) fue cuando me mando el error, el cual es: "DeletedApiProjectMapError", posteriormente probé con la mía y funciono, después puse la que se encuentra en su git y me dio el error "RefererNotAllowedMapError" 🤔

**Comment by grupohernandezalba** [comment]
Hola, si tienes razón, aun no doy de alta los permisos de la APi Key en la
Consola. Lo hago mañana Lunes y lo vemos en clase.

**Comment by LGsusMx** [comment]
Ya funciona profe, muchas gracias!

**Comment by grupohernandezalba** [comment]
Muy bien Jesus , te recomiendo sigas conociendo más de Bootstrap4.
