### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [LGsusMx/GeoReferenciados-Practica1#3]
Muy bien Jesus, si te es posible trata de implementar la opción de editar. De preferencia usa los botones y colores Bootstrap ya que el color negro en botón es poco usado para denotar acciones.
![Captura de Pantalla 2020-03-12 a la(s) 22 08 35](https://user-images.githubusercontent.com/14998558/76588972-3422bb80-64ae-11ea-9166-23a49320128a.png)

**Comment by LGsusMx** [comment]
Profesor he implementado la opción de editar y una nueva interfaz, cuando tenga tiempo dele un vistazo 👍

**Comment by grupohernandezalba** [comment]
Muy bien, lo checo.
